[CMSO-1336] Document how to use the SDK with working examples.
pantheon-systems/customer-secrets-php-sdk pull request #8
Opened 2023-05-04 16:36 UTC by kporras07

2023-05-04 17:56 UTC, greg-1-anderson commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
This location is in the [WordPress Composer-Managed .gitignore file](https://github.com/pantheon-upstreams/wordpress-composer-managed/blob/main/.gitignore#L73).

2023-05-04 18:01 UTC, greg-1-anderson requested changes
Can we use the Drupal [configuraiton override system](https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system), and just tell folks to override the secret in their settings.php file? Is there any reason why that won't work?

Let's work out the .gitignore issue / custom plugin commit location with CMSP; the WordPress example is otherwise just fine.

2023-05-04 18:05 UTC, kporras07 commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
Yeah, therefore my Note about "unignoring it":

`!web/app/plugins/my-plugin`

Maybe I should call it out more explicitly?

2023-05-04 18:08 UTC, kporras07 commented
For WP, I got verbal approval from Chris during the work session today about my note in the instructions.

re:Drupal. I followed that same guide (https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system#s-providing-overrides-from-modules) but I'd like to avoid doing this sort of stuff in settings.php because it will run on EVERY page (and even ajax) load (also, tbh I don't know if we have access to everything we need in that bootstrap stage, but probably yes). Using the current approach will make the code run only when the config item is being retrieved

Any thoughts?

2023-05-04 21:23 UTC, greg-1-anderson commented
> Any thoughts?

We cache the results for 15m, so it wouldn't be horrible to load on every page. The module solution is much better, of course. Maybe have a one-line example showing the settings.php use case, and then continue with the preferred module implementation? My feeling is that most folks will use the key module, but if someone just wants to do a quick experiment to see if it works before investing more time, it's nice to have the ability to just throw a few lines into settings.php and get results.

2023-05-04 21:26 UTC, greg-1-anderson commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
I'd prefer it if CMSP provided a location for custom plugins that is not ignored by default. Failing that, adding a line in the docs with the same path as the demo (`!web/app/plugins/secrets-demo`) would be helpful. I missed the .gitignore note on the second half of the line above; presumably, someone actually following the guide would catch it as-is, but not everyone knows about `!` rules.

2023-05-04 21:33 UTC, jazzsequence commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
The `.gitignore` file explicitly calls this out. The assumption is that if you're using Composer to manage your plugins, we ignore `web/app/plugins` by default and you should _un_-ignore your custom code.
https://github.com/pantheon-systems/wordpress-composer-managed/blob/default/.gitignore#LL67C1-L74C26

2023-05-04 21:47 UTC, jazzsequence commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
Also `!web/app/plugins/custom` would not work because WordPress would assume `custom` was a broken plugin (no main plugin file) and there isn't really a context in WordPress to allow multiple locations for plugins to be stored.

2023-05-05 13:25 UTC, kporras07 commented on docs/wordpress-example.md
> +    git add web/app/plugins/secets-demo
I added explicit instructions to add stuff to .gitignore to be able to add the plugin

2023-05-10 20:53 UTC, greg-1-anderson approved these changes

2023-05-10 20:54 UTC, merged